class RootWindow(tk.Tk):
    def __init__(self, top=None):
        top.geometry("1280x720+298+185")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#000080")
        top.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.328, rely=0.028, relheight=0.944, relwidth=0.656)
        self.Canvas1.configure(background="#ffffff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.038, rely=0.042, height=41, width=320)
        self.Label1.configure(activebackground="#000080")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(background="#000080")
        self.Label1.configure(font="-family {Consolas} -size 18")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''МЕТОД ПОСТРОЕНИЯ''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.039, rely=0.493, height=18, width=81)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#000080")
        self.Label3.configure(font="-family {Consolas} -size 14")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(text='''Xн''')

        self.Button1_14 = tk.Button(top)
        self.Button1_14.place(relx=0.039, rely=0.861, height=29, width=320)
        self.Button1_14.configure(activebackground="#f9f9f9")
        self.Button1_14.configure(font="-family {Consolas} -size 14")
        self.Button1_14.configure(text='''Сравнение алгоритмов''')

        self.Button1_15 = tk.Button(top)
        self.Button1_15.place(relx=0.039, rely=0.917, height=29, width=320)
        self.Button1_15.configure(activebackground="#f9f9f9")
        self.Button1_15.configure(font="-family {Consolas} -size 14")
        self.Button1_15.configure(text='''Очистить экран''')

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.039, rely=0.097, relheight=0.125, relwidth=0.25)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="-family {Consolas} -size 14")
        self.Listbox1.configure(selectbackground="#c4c4c4")

        self.Label1_4 = tk.Label(top)
        self.Label1_4.place(relx=0.039, rely=0.235, height=41, width=320)
        self.Label1_4.configure(activebackground="#000080")
        self.Label1_4.configure(activeforeground="white")
        self.Label1_4.configure(background="#000080")
        self.Label1_4.configure(font="-family {Consolas} -size 18")
        self.Label1_4.configure(foreground="#ffffff")
        self.Label1_4.configure(text='''ЦВЕТ ПОСТРОЕНИЯ''')

        self.Listbox1_5 = tk.Listbox(top)
        self.Listbox1_5.place(relx=0.039, rely=0.292, relheight=0.125, relwidth=0.25)
        self.Listbox1_5.configure(background="white")
        self.Listbox1_5.configure(font="-family {Consolas} -size 14")
        self.Listbox1_5.configure(selectbackground="#c4c4c4")

        self.Label1_5 = tk.Label(top)
        self.Label1_5.place(relx=0.039, rely=0.432, height=41, width=320)
        self.Label1_5.configure(activebackground="#000080")
        self.Label1_5.configure(activeforeground="white")
        self.Label1_5.configure(background="#000080")
        self.Label1_5.configure(font="-family {Consolas} -size 18")
        self.Label1_5.configure(foreground="#ffffff")
        self.Label1_5.configure(text='''КООРДИНАТЫ ЛИНИИ''')

        self.Label3_6 = tk.Label(top)
        self.Label3_6.place(relx=0.102, rely=0.493, height=18, width=80)
        self.Label3_6.configure(activebackground="#f9f9f9")
        self.Label3_6.configure(background="#000080")
        self.Label3_6.configure(font="-family {Consolas} -size 14")
        self.Label3_6.configure(foreground="#ffffff")
        self.Label3_6.configure(text='''Yн''')

        self.Label3_7 = tk.Label(top)
        self.Label3_7.place(relx=0.164, rely=0.493, height=18, width=81)
        self.Label3_7.configure(activebackground="#f9f9f9")
        self.Label3_7.configure(background="#000080")
        self.Label3_7.configure(font="-family {Consolas} -size 14")
        self.Label3_7.configure(foreground="#ffffff")
        self.Label3_7.configure(text='''Xк''')

        self.Label3_8 = tk.Label(top)
        self.Label3_8.place(relx=0.227, rely=0.493, height=18, width=80)
        self.Label3_8.configure(activebackground="#f9f9f9")
        self.Label3_8.configure(background="#000080")
        self.Label3_8.configure(font="-family {Consolas} -size 14")
        self.Label3_8.configure(foreground="#ffffff")
        self.Label3_8.configure(text='''Yк''')

        self.Spinbox1 = tk.Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.039, rely=0.521, relheight=0.042, relwidth=0.063)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(font="-family {Consolas} -size 14")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(relief="flat")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(textvariable=cg_lab_03_support.spinbox)

        self.Spinbox1_9 = tk.Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox1_9.place(relx=0.102, rely=0.521, relheight=0.043, relwidth=0.063)
        self.Spinbox1_9.configure(activebackground="#f9f9f9")
        self.Spinbox1_9.configure(background="white")
        self.Spinbox1_9.configure(font="-family {Consolas} -size 14")
        self.Spinbox1_9.configure(highlightbackground="black")
        self.Spinbox1_9.configure(relief="flat")
        self.Spinbox1_9.configure(selectbackground="#c4c4c4")
        self.Spinbox1_9.configure(textvariable=cg_lab_03_support.spinbox)

        self.Spinbox1_10 = tk.Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox1_10.place(relx=0.165, rely=0.521, relheight=0.043, relwidth=0.063)
        self.Spinbox1_10.configure(activebackground="#f9f9f9")
        self.Spinbox1_10.configure(background="white")
        self.Spinbox1_10.configure(font="-family {Consolas} -size 14")
        self.Spinbox1_10.configure(highlightbackground="black")
        self.Spinbox1_10.configure(relief="flat")
        self.Spinbox1_10.configure(selectbackground="#c4c4c4")
        self.Spinbox1_10.configure(textvariable=cg_lab_03_support.spinbox)

        self.Spinbox1_11 = tk.Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox1_11.place(relx=0.227, rely=0.521, relheight=0.043, relwidth=0.063)
        self.Spinbox1_11.configure(activebackground="#f9f9f9")
        self.Spinbox1_11.configure(background="white")
        self.Spinbox1_11.configure(font="-family {Consolas} -size 14")
        self.Spinbox1_11.configure(highlightbackground="black")
        self.Spinbox1_11.configure(relief="flat")
        self.Spinbox1_11.configure(selectbackground="#c4c4c4")
        self.Spinbox1_11.configure(textvariable=cg_lab_03_support.spinbox)

        self.Button1_12 = tk.Button(top)
        self.Button1_12.place(relx=0.039, rely=0.574, height=28, width=320)
        self.Button1_12.configure(activebackground="#f9f9f9")
        self.Button1_12.configure(font="-family {Consolas} -size 14")
        self.Button1_12.configure(text='''Нарисовать линию''')

        self.Label1_6 = tk.Label(top)
        self.Label1_6.place(relx=0.039, rely=0.625, height=41, width=320)
        self.Label1_6.configure(activebackground="#000080")
        self.Label1_6.configure(activeforeground="white")
        self.Label1_6.configure(background="#000080")
        self.Label1_6.configure(font="-family {Consolas} -size 18")
        self.Label1_6.configure(foreground="#ffffff")
        self.Label1_6.configure(text='''ПАРАМЕТРЫ ПУЧКА''')

        self.Label3_1 = tk.Label(top)
        self.Label3_1.place(relx=0.039, rely=0.681, height=18, width=162)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(background="#000080")
        self.Label3_1.configure(font="-family {Consolas} -size 14")
        self.Label3_1.configure(foreground="#ffffff")
        self.Label3_1.configure(text='''Радиус''')

        self.Label3_2 = tk.Label(top)
        self.Label3_2.place(relx=0.162, rely=0.681, height=18, width=163)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(background="#000080")
        self.Label3_2.configure(font="-family {Consolas} -size 14")
        self.Label3_2.configure(foreground="#ffffff")
        self.Label3_2.configure(text='''Шаги''')

        self.Spinbox1_3 = tk.Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox1_3.place(relx=0.039, rely=0.711, relheight=0.042, relwidth=0.125)
        self.Spinbox1_3.configure(activebackground="#f9f9f9")
        self.Spinbox1_3.configure(background="white")
        self.Spinbox1_3.configure(font="-family {Consolas} -size 14")
        self.Spinbox1_3.configure(highlightbackground="black")
        self.Spinbox1_3.configure(relief="flat")
        self.Spinbox1_3.configure(selectbackground="#c4c4c4")
        self.Spinbox1_3.configure(textvariable=cg_lab_03_support.spinbox)

        self.Spinbox1_4 = tk.Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox1_4.place(relx=0.165, rely=0.711, relheight=0.042, relwidth=0.125)
        self.Spinbox1_4.configure(activebackground="#f9f9f9")
        self.Spinbox1_4.configure(background="white")
        self.Spinbox1_4.configure(font="-family {Consolas} -size 14")
        self.Spinbox1_4.configure(highlightbackground="black")
        self.Spinbox1_4.configure(relief="flat")
        self.Spinbox1_4.configure(selectbackground="#c4c4c4")
        self.Spinbox1_4.configure(textvariable=cg_lab_03_support.spinbox)

        self.Button1_11 = tk.Button(top)
        self.Button1_11.place(relx=0.039, rely=0.764, height=29, width=320)
        self.Button1_11.configure(activebackground="#f9f9f9")
        self.Button1_11.configure(font="-family {Consolas} -size 14")
        self.Button1_11.configure(text='''Построить пучок''')


if __name__ == '__main__':
    vp_start_gui()
